name: Daily Export of Baidu Tongji Data

on:
  schedule:
    - cron: '30 11 * * *' # UTC Time, Beijing Time: 19:30
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Add Mask
      run: |
        echo "::add-mask::${{ secrets.BAIDU_TONGJI_REFRESH_TOKEN }}"
        echo "::add-mask::${{ secrets.BAIDU_TONGJI_ACCESS_TOKEN }}"
        echo "::add-mask::${{ secrets.BAIDU_TONGJI_API_KEY }}"
        echo "::add-mask::${{ secrets.BAIDU_TONGJI_SECRET_KEY }}"
        echo "::add-mask::${{ secrets.REPO_ACCESS_TOKEN }}"
        echo "::add-mask::${{ secrets.GIT_EMAIL }}"
        echo "::add-mask::${{ secrets.GIT_USERNAME }}"
    - name: Clone Baidu Tongji Exporter
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Clone Data Repo
      env:
        BAIDU_TONGJI_ACCESS_TOKEN: ${{ secrets.BAIDU_TONGJI_ACCESS_TOKEN }}
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global credential.helper cache
        git clone https://${{secrets.REPO_ACCESS_TOKEN}}@github.com/${{secrets.REPO_NAME}} data
        python cli.py fetch -p ./data
        cd data
        git add .
        git commit -m "$(TZ=Asia/Shanghai date)"
        git push
